name: NodeJS Backend Service CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: |
        cd backend
        pnpm install

    - name: Start backend service
      run: |
        cd backend
        pnpm start &  # Start service in the background
        sleep 10      # Wait for it to initialize

    - name: Test backend service
      run: curl http://localhost:3000/user/
