name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Step 2.1: Install pnpm
    - name: Install pnpm
      run: npm install -g pnpm

    # Step 3: Navigate to the backend directory and install dependencies
    - name: Install dependencies
      working-directory: ./backend
      run: pnpm install

    # Step 4: Build the project
    - name: Build the project
      working-directory: ./backend
      env:
        APP_ENV: ${{ secrets.APP_ENV }}
        PORT: ${{ secrets.PORT }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
        JWT_REFRESH_EXPIRES_IN: ${{ secrets.JWT_REFRESH_EXPIRES_IN }}
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_SERVICE: ${{ secrets.MAIL_SERVICE }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_FROM: ${{ secrets.MAIL_FROM }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      run: pnpm build

    # Step 5: Start the application
    - name: Start the application
      working-directory: ./backend
      env:
        APP_ENV: ${{ secrets.APP_ENV }}
        PORT: ${{ secrets.PORT }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
        JWT_REFRESH_EXPIRES_IN: ${{ secrets.JWT_REFRESH_EXPIRES_IN }}
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_SERVICE: ${{ secrets.MAIL_SERVICE }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_FROM: ${{ secrets.MAIL_FROM }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      run: pnpm start
