name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm  # Install pnpm globally

    - name: Install dependencies and build
      run: |
        cd backend  # Navigate to the backend directory
        pnpm install  # Install dependencies using pnpm
        pnpm run build  # Run the build script using pnpm

    - name: Run backend service
      run: |
        cd backend
        nohup pnpm start &  # Start the backend service in the background

    - name: Verify backend service is running
      run: |
        curl http://localhost:3000/user  # Ensure the service is up

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./backend/dist/*  # Specify the files to include in the release (adjust this as needed)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify Slack about deployment status
      uses: slackapi/slack-github-action@v1.16.0
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channel: "#your-channel-id"
        text: "Deployment completed successfully!"
