name: Backend CI/CD Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: |
        cd backend
        pnpm install

    - name: Build backend service
      run: |
        cd backend
        pnpm build

    - name: Start backend service
      run: |
        cd backend
        pnpm start &  # Start the service in the background
        sleep 10      # Wait for the service to initialize

    - name: Test backend service
      run: curl http://localhost:3000/user
